--------------------------------------------------------
--  DDL for Table BON
--------------------------------------------------------

  CREATE TABLE "DVD"."BON" 
   (	"ID" NUMBER(*,0), 
	"DATA" DATE, 
	"COD_CLIENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.BON
SET DEFINE OFF;
Insert into DVD.BON (ID,DATA,COD_CLIENT) values (1,to_date('04-AUG-15','DD-MON-RR'),1);
--------------------------------------------------------
--  DDL for Index BON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."BON_PK" ON "DVD"."BON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BON
--------------------------------------------------------

  ALTER TABLE "DVD"."BON" ADD CONSTRAINT "BON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."BON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BON
--------------------------------------------------------

  ALTER TABLE "DVD"."BON" ADD CONSTRAINT "BON_CLIENT" FOREIGN KEY ("COD_CLIENT")
	  REFERENCES "DVD"."CLIENT" ("ID") ENABLE;
    
--------------------------------------------------------
--  DDL for Table CATEGORIE
--------------------------------------------------------

  CREATE TABLE "DVD"."CATEGORIE" 
   (	"ID" NUMBER(*,0), 
	"DENUMIRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.CATEGORIE
SET DEFINE OFF;
Insert into DVD.CATEGORIE (ID,DENUMIRE) values (1,'SF');
--------------------------------------------------------
--  DDL for Index CATEGORIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."CATEGORIE_PK" ON "DVD"."CATEGORIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIE
--------------------------------------------------------

  ALTER TABLE "DVD"."CATEGORIE" ADD CONSTRAINT "CATEGORIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."CATEGORIE" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "DVD"."CLIENT" 
   (	"ID" NUMBER(*,0), 
	"NUME" VARCHAR2(50 BYTE), 
	"ADRESA" VARCHAR2(100 BYTE), 
	"COD_ORAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.CLIENT
SET DEFINE OFF;
Insert into DVD.CLIENT (ID,NUME,ADRESA,COD_ORAS) values (1,'Gigel','AFI3',1);
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."CLIENT_PK" ON "DVD"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "DVD"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "DVD"."CLIENT" ADD CONSTRAINT "ORAS_CLIENT" FOREIGN KEY ("COD_ORAS")
	  REFERENCES "DVD"."ORAS" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "DVD"."FILM" 
   (	"ID" NUMBER(*,0), 
	"TITLU" VARCHAR2(100 BYTE), 
	"DESCRIERE" VARCHAR2(2000 BYTE), 
	"DURATA" NUMBER(*,0), 
	"NUMAR_EXEMPLARE" NUMBER(*,0), 
	"TARIF_ZILNIC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.FILM
SET DEFINE OFF;
Insert into DVD.FILM (ID,TITLU,DESCRIERE,DURATA,NUMAR_EXEMPLARE,TARIF_ZILNIC) values (1,'Fast 7','Actiune',135,3,20);
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."FILM_PK" ON "DVD"."FILM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "DVD"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."FILM" MODIFY ("ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table FILM_CATEG
--------------------------------------------------------

  CREATE TABLE "DVD"."FILM_CATEG" 
   (	"ID" NUMBER(*,0), 
	"COD_DVD" NUMBER(*,0), 
	"COD_CATEGORIE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.FILM_CATEG
SET DEFINE OFF;
Insert into DVD.FILM_CATEG (ID,COD_DVD,COD_CATEGORIE) values (1,1,1);
--------------------------------------------------------
--  DDL for Index FILM_CATEG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."FILM_CATEG_PK" ON "DVD"."FILM_CATEG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FILM_CATEG
--------------------------------------------------------

  ALTER TABLE "DVD"."FILM_CATEG" ADD CONSTRAINT "FILM_CATEG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."FILM_CATEG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FILM_CATEG
--------------------------------------------------------

  ALTER TABLE "DVD"."FILM_CATEG" ADD CONSTRAINT "CATEGORIE" FOREIGN KEY ("COD_CATEGORIE")
	  REFERENCES "DVD"."CATEGORIE" ("ID") ENABLE;
  ALTER TABLE "DVD"."FILM_CATEG" ADD CONSTRAINT "CATEGORIE_FILM" FOREIGN KEY ("COD_DVD")
	  REFERENCES "DVD"."FILM" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for Table INCHIRIERE
--------------------------------------------------------

  CREATE TABLE "DVD"."INCHIRIERE" 
   (	"ID" NUMBER(*,0), 
	"COD_BON" NUMBER(*,0), 
	"COD_FILM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.INCHIRIERE
SET DEFINE OFF;
Insert into DVD.INCHIRIERE (ID,COD_BON,COD_FILM) values (1,1,1);
--------------------------------------------------------
--  DDL for Index INCHIRIERE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."INCHIRIERE_PK" ON "DVD"."INCHIRIERE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INCHIRIERE
--------------------------------------------------------

  ALTER TABLE "DVD"."INCHIRIERE" ADD CONSTRAINT "INCHIRIERE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."INCHIRIERE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table INCHIRIERE
--------------------------------------------------------

  ALTER TABLE "DVD"."INCHIRIERE" ADD CONSTRAINT "INCHIRIERE_BON" FOREIGN KEY ("COD_BON")
	  REFERENCES "DVD"."BON" ("ID") ENABLE;
  ALTER TABLE "DVD"."INCHIRIERE" ADD CONSTRAINT "INCHIRIERE_FILM" FOREIGN KEY ("COD_FILM")
	  REFERENCES "DVD"."FILM" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for Table ORAS
--------------------------------------------------------

  CREATE TABLE "DVD"."ORAS" 
   (	"ID" NUMBER(*,0), 
	"NUME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DVD.ORAS
SET DEFINE OFF;
Insert into DVD.ORAS (ID,NUME) values (2,'BUZAU');
Insert into DVD.ORAS (ID,NUME) values (1,'BUCURESTI');
Insert into DVD.ORAS (ID,NUME) values (4,'Timisoara');
Insert into DVD.ORAS (ID,NUME) values (3,'Brasov');
--------------------------------------------------------
--  DDL for Index ORAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DVD"."ORAS_PK" ON "DVD"."ORAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORAS
--------------------------------------------------------

  ALTER TABLE "DVD"."ORAS" ADD CONSTRAINT "ORAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DVD"."ORAS" MODIFY ("ID" NOT NULL ENABLE);

